export const FUNCTION_VI = {
    filterTL: 'Lọc',
    clearTL: 'Làm mới',
    imageTL: 'Hình ảnh',
    nameTL: 'Tên',
    priceTL: 'Giá',
    productDescriptionTL: 'Mô tả sản phẩm',
    inventoryTL: 'Hàng tồn kho',
    buttonTL: 'Chức năng',
    customerTL: 'Khách hàng',
    quantityTL: 'Số lượng',
    statusTL: 'Trạng thái',
    shippingUnit: 'Đơn vị vận chuyển',
    typeTL: 'Kiểu khách hàng',
    levelTL: 'Xếp hạng',
    addProductTL: 'Thêm sản phẩm',
    updateProductTL: 'Chỉnh sửa sản phẩm',
    deleteProductTL: 'xóa sản phẩm',
}

