export const MAIN_EN = {
    profileTL: 'Profile',
    homeTL: 'Home',
    productManagementTL: 'Product Management',
    listOfProductsTL: 'List of Product',
    inventoryTL: 'Inventory',
    orderManagementTL: 'Order Management',
    listOfOrdersTL: 'List of Orders',
    customerManagementTL: 'Customer Management',
    listOfCustomersTL: 'List of Customers',
    customerCareTL: 'Customer Care',
    reportingAndAnalysisTL: 'Reporting and Analysis',
    salesReportTL: 'Sales Report',
    performanceAnalysisTL: 'Performance Analysis',
    inventoryManagementTL: 'Inventory Management',
    exportImportWarehouseTL: 'Export/Import Warehouse',
    warehouseInventoryTL: 'Warehouse Inventory',
    shippingIntegrationTL: 'Shipping Integration',
    notificationTL: 'Notification',
}